workflows:
  android-tv-release:
    name: Android TV App
    max_build_duration: 10
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Build APK
        script: |
          ./gradlew wrapper
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
