workflows:
  android-app:
    name: Build Exodus WebView TV App
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.example.exoduswrapper"
      android_signing:
        - release_keystore
      java: 17
    scripts:
      - name: Set up Android SDK
        script: |
          echo "y" | sdkmanager "platforms;android-33"
          echo "y" | sdkmanager "build-tools;33.0.0"
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
