workflows:
  android-app:
    name: Build Exodus WebView TV App
    max_build_duration: 15
    environment:
      java: 17
    scripts:
      - name: Build Debug APK
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
